spring:
  data:
    mongodb:
      uri: mongodb+srv://criss2001david:root@cluster0.4pnls.mongodb.net/blackjackroyale?retryWrites=true&w=majority&appName=Cluster0
  main:
    allow-bean-definition-overriding: true
  server:
    port: 8080
    address: 0.0.0.0
    servlet:
      context-path: /
