spring:
  security:
    oauth2:
      client:
        provider:
          azure:
            issuer-uri: https://login.microsoftonline.com/c64f33f5-c52f-437e-a331-0fc5f8e5058a/v2.0
        registration:
          azure-dev:
            provider: azure
            client-id: 066fef70-45bd-422a-a870-149ae2f088f4
            client-secret: 
              - openid
              - email
              - profile

  data:
    mongodb:
      uri: mongodb+srv://santiagotorresacosta29:rH9ITs8F4cbNdMxf@arep.lcigk.mongodb.net/BlackJack?retryWrites=true&w=majority&appName=AREP


