# Configuración de la conexión a MongoDB
spring:
  data:
    mongodb:
      uri: mongodb+srv://santiagotorresacosta29:rH9ITs8F4cbNdMxf@arep.lcigk.mongodb.net/BlackJack?retryWrites=true&w=majority&appName=AREP

# Habilitar el modo de depuración
debug=true
