name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama principal

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: cristindavid0124/mi-backend:latest  # Usa tu imagen de Docker Hub

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy to Azure App Service
      env:
        AZURE_WEBAPP_NAME: "BlackJackRoyaleBackend"  # Nombre del App Service en Azure
        AZURE_RESOURCE_GROUP: "BlackJackRoyaleApp_group"  # Nombre del grupo de recursos en Azure
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        az login --service-principal --username $AZURE_USERNAME --password $AZURE_PASSWORD --tenant $AZURE_TENANT_ID
        az webapp config container set \
          --name BlackJackRoyaleBackend \
          --resource-group BlackJackRoyaleApp_group \
          --docker-custom-image-name cristindavid0124/mi-backend:latest \
          --docker-registry-server-url https://index.docker.io/v1/
